#!/bin/bash

for file in file_name{{1..3}.md,1.textdoc}; do
	if [ $file == "file_name1.md" ]; then 
		mv $file "file_name1.textdoc";
		echo "$file --> file_name1.textdoc";

	fi
	
	if [ $file == "file_name2.md" ]; then
		mv $file "file_name2";
		echo "$file --> file_name2";
	fi
	
	if [ $file == "file_name3.md" ]; then
		mv $file "file_name3.md.latest";
		echo "$file --> file_name3.md.latest";
	fi

	if [ $file == "file_name1.textdoc" ]; then
		mv $file "file_name1.txt";
		echo "$file --> file_name1.txt";
	fi;
done
