#!/bin/bash

makeList () {
printf "    %s    \t     %s     \t%s\t     %s     \t          %s\n" "DATE" "TIME" "REQ" "IP" "URL"

cat $1 | awk '{printf "%s %s %s\n", substr($4,2,16), $1, $7}'| sort | uniq -c | awk '{if ($1 > 50) {printf "%s %s %d %s %s\n", substr($2,1,11), substr($2,13,4), $1, $3, $4}}' > temp

while read line; do
echo $line | awk '{printf "%s\t%02d:%02d - %02d:%02d\t%d\t%s\t%s\n", $1, substr($2,1,2), substr($2,4,1)*10, substr($2,4,1) < 5 ? substr($2,1,2) : (substr($2,1,2) < 23 ? substr($2,1,2)+1 : 0), substr($2,4,1) < 5 ? (substr($2,4,1)+1)*10 :0, $3, $4, $5}';
done < temp

rm temp
}

makeList $1 > output_
cat output_ | awk '{if (NR !=1) {print $6}}' | sort | uniq 


 
